apiVersion: v1
kind: Secret
metadata:
  name: sql
  namespace: api-dev
type: Opaque
data:
  SQL_USER: c3FsYWRtaW5nVG8wMjE2
  SQL_PASSWORD: bkcybWE1Sm04
  SQL_SERVER: c3Fsc2VydmVyZ3RvMDIxNi5kYXRhYmFzZS53aW5kb3dzLm5ldA==
  SQL_DBNAME: bXlkcml2aW5nREI=