apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-java
  name: user-java
  namespace: api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - image: registrygto0216.azurecr.io/user-java:latest
        name: user-java
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: sql
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-java
  name: user-java
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: user-java